name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    # These actions are defined in their own repos 
    # https://github.com/actions/first-interaction
    # inside this you can go to actions.yml and see how and what the inputs are
    # Using the github sdk you will be able to access the input programmatically https://github.com/actions/first-interaction/blob/main/action.yml
    # see the dockerfile and whats being built and how its being built
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Message that will be displayed on users' first issue"
        pr-message: "Message that will be displayed on users' first pull request"
